spring:
  config:
    activate:
      on-profile: dev
  application:
    name: inflace
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

redis:
  host: ${INFLACE_VALKEY_URL}
  port: ${INFLACE_VALKEY_PORT}
  database: 0

cookie:
  same-site: None
  secure: true

cors:
  allowed:
    origins:
      - https://inflace.site
      - http://localhost:3000
