spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: inflace
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /api-docs
    url: /v3/api-docs

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  redirect-uri: ${GOOGLE_REDIRECT_URI}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

youtube:
  data-api:
    base-url: ${DATA_API_URL}
    api-key: ${DATA_API_KEY}
  analytics-api:
    base-url: ${ANALYTICS_API_URL}
    access-token: ${ANALYTICS_TEST_ACCESS_TOKEN}
  oauth:
    redirect-uri: ${YOUTUBE_REDIRECT_URI}