spring:
  profiles:
    default: local
  application:
    name: inflace
  docker:
    compose:
      enabled: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    out-of-order: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /api-docs
    url: /v3/api-docs

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  redirect-uri: ${GOOGLE_REDIRECT_URI}

youtube:
  data-api:
    base-url: ${DATA_API_URL}
    api-key: ${DATA_API_KEY}
  analytics-api:
    base-url: ${ANALYTICS_API_URL}
    access-token: ${ANALYTICS_TEST_ACCESS_TOKEN}
  oauth:
    redirect-uri: ${YOUTUBE_REDIRECT_URI}
