insert into youtube_category (youtube_category_id, title, assignable, created_at, updated_at)
values
    (1, '영화/애니메이션', true, current_timestamp, current_timestamp),
    (2, '자동차', true, current_timestamp, current_timestamp),
    (10, '음악', true, current_timestamp, current_timestamp),
    (15, '반려동물/동물', true, current_timestamp, current_timestamp),
    (17, '스포츠', true, current_timestamp, current_timestamp),
    (18, '단편 영화', false, current_timestamp, current_timestamp),
    (19, '여행/이벤트', true, current_timestamp, current_timestamp),
    (20, '게임', true, current_timestamp, current_timestamp),
    (21, '동영상 블로그', false, current_timestamp, current_timestamp),
    (22, '인물/블로그', true, current_timestamp, current_timestamp),
    (23, '코미디', true, current_timestamp, current_timestamp),
    (24, '엔터테인먼트', true, current_timestamp, current_timestamp),
    (25, '뉴스/정치', true, current_timestamp, current_timestamp),
    (26, '노하우/스타일', true, current_timestamp, current_timestamp),
    (27, '교육', true, current_timestamp, current_timestamp),
    (28, '과학기술', true, current_timestamp, current_timestamp),
    (30, '영화', false, current_timestamp, current_timestamp),
    (31, '애니메/애니메이션', false, current_timestamp, current_timestamp),
    (32, '액션/모험', false, current_timestamp, current_timestamp),
    (33, '고전', false, current_timestamp, current_timestamp),
    (34, '코미디', false, current_timestamp, current_timestamp),
    (35, '다큐멘터리', false, current_timestamp, current_timestamp),
    (36, '드라마', false, current_timestamp, current_timestamp),
    (37, '가족', false, current_timestamp, current_timestamp),
    (38, '외국', false, current_timestamp, current_timestamp),
    (39, '공포', false, current_timestamp, current_timestamp),
    (40, 'SF/판타지', false, current_timestamp, current_timestamp),
    (41, '스릴러', false, current_timestamp, current_timestamp),
    (42, '단편', false, current_timestamp, current_timestamp),
    (43, '프로그램', false, current_timestamp, current_timestamp),
    (44, '예고편', false, current_timestamp, current_timestamp);
